//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConditionCalculator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractCondition
    {
        public int Id { get; set; }
        public int Do { get; set; }
        public bool IsTrueOperantOne { get; set; }
        public System.Guid OperantOne { get; set; }
        public bool IsTrueOperantTwo { get; set; }
        public System.Guid OperantTwo { get; set; }
        public int ContractorItemId { get; set; }
    
        public virtual ContractItem ContractItem { get; set; }
        public virtual OperandTask OperandOne { get; set; }
        public virtual OperandTask OperandTwo { get; set; }
        public virtual Variant Variant { get; set; }
    }
}
