//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConditionCalculator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractItem()
        {
            this.Relationships = new HashSet<Relationship>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public System.Guid ContractUid { get; set; }
        public int TypeValueId { get; set; }
        public decimal Factor { get; set; }
        public Nullable<decimal> FixValue { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual TypeValue TypeValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relationship> Relationships { get; set; }
    }
}
