//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConditionCalculator.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConditionCalculatorEntities : DbContext
    {
        public ConditionCalculatorEntities()
            : base("name=ConditionCalculatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<ContractItem> ContractItems { get; set; }
        public virtual DbSet<OperandTask> OperandTasks { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<TypeTask> TypeTasks { get; set; }
        public virtual DbSet<TypeValue> TypeValues { get; set; }
        public virtual DbSet<TypeSettlement> TypeSettlements { get; set; }
    }
}
