//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConditionCalculator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public int Id { get; set; }
        public int ContractItemId { get; set; }
        public int TaskId { get; set; }
        public bool IsTrue { get; set; }
    
        public virtual ContractItem ContractItem { get; set; }
        public virtual TypeTask TypeTask { get; set; }
    }
}
